// preload.js
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  // actions
  downloadAudio: (url, format, opts = {}) =>
    ipcRenderer.send('download-audio', {
      url,
      format,
      playlist: !!opts.playlist,
      subtitles: !!opts.subtitles,
      cookiesBrowser: opts.cookiesBrowser || 'none',
      formatId: opts.formatId || null,
      startTime: opts.startTime || null,
      endTime: opts.endTime || null,
      resume: opts.resume !== false,
      prefetchedMeta: opts.prefetchedMeta || null,
    }),
  probeFormats: (url) => ipcRenderer.invoke('probe-formats', url),
  probeFast: (url) => ipcRenderer.invoke('probe-fast', url),
  readClipboard: () => require('electron').clipboard.readText(),
  detectBrowsers: () => ipcRenderer.invoke('detect-browsers'),
  extensionFolder: (browser) => ipcRenderer.invoke('extension-folder', browser),
  openExtensionInstaller: (browser) => ipcRenderer.invoke('open-extension-installer', browser),
  launchWithExtension: (browser) => ipcRenderer.invoke('launch-with-extension', browser),
  installNativeHost: () => ipcRenderer.invoke('install-native-host'),
  importChromeCookies: (opts) => ipcRenderer.invoke('import-chrome-cookies', opts || {}),
  getSiteDefault: (url) => ipcRenderer.invoke('get-site-default', url),
  setSiteDefault: (url, format) => ipcRenderer.invoke('set-site-default', { url, format }),
  savePlayPosition: (filepath, pos, duration) => ipcRenderer.invoke('save-play-position', { filepath, pos, duration }),
  getPlayPosition: (filepath) => ipcRenderer.invoke('get-play-position', filepath),
  fileExists: (filepath) => ipcRenderer.invoke('file-exists', filepath),
  reconcileLibrary: () => ipcRenderer.invoke('reconcile-library'),
  fileHash: (filepath) => ipcRenderer.invoke('file-hash', filepath),
  probeCacheGet: (url) => ipcRenderer.invoke('probe-cache-get', url),
  probeCacheSet: (url, data) => ipcRenderer.invoke('probe-cache-set', { url, data }),
  fetchLyrics: (artist, title, duration, album) => ipcRenderer.invoke('fetch-lyrics', { artist, title, duration, album }),
  getActivityLog: () => ipcRenderer.invoke('get-activity-log'),
  clearActivityLog: () => ipcRenderer.invoke('clear-activity-log'),
  incrementPlayCount: (filepath) => ipcRenderer.invoke('increment-play-count', filepath),
  getPlayCounts: () => ipcRenderer.invoke('get-play-counts'),
  readMetadata: (filepath) => ipcRenderer.invoke('read-metadata', filepath),
  writeMetadata: (filepath, tags) => ipcRenderer.invoke('write-metadata', { filepath, tags }),
  recordBrowseVisit: (payload) => ipcRenderer.invoke('record-browse-visit', payload),
  getBrowseHistory: () => ipcRenderer.invoke('get-browse-history'),
  clearBrowseHistory: () => ipcRenderer.invoke('clear-browse-history'),
  getAppInfo: () => ipcRenderer.invoke('get-app-info'),
  listChannels: () => ipcRenderer.invoke('list-channels'),
  addChannel: (payload) => ipcRenderer.invoke('add-channel', payload),
  removeChannel: (id) => ipcRenderer.invoke('remove-channel', id),
  onChannelTrigger: (cb) => ipcRenderer.on('channel-trigger', (_e, data) => cb(data)),
  getQueueState: () => ipcRenderer.invoke('get-queue-state'),
  reorderQueue: (ids) => ipcRenderer.send('reorder-queue', ids),
  cancelDownloadById: (id) => ipcRenderer.send('cancel-download', id),
  onQueueState: (cb) => ipcRenderer.on('queue-state', (_e, data) => cb(data)),
  diskFree: (dir) => ipcRenderer.invoke('disk-free', dir),
  checkDuplicate: (url) => ipcRenderer.invoke('check-duplicate', url),
  pickFolder: (title) => ipcRenderer.invoke('pick-folder', title),
  onDeepLink: (cb) => ipcRenderer.on('deep-link-url', (_e, url) => cb(url)),
  onWatchFolderUrls: (cb) => ipcRenderer.on('watch-folder-urls', (_e, urls) => cb(urls)),
  onScheduledTrigger: (cb) => ipcRenderer.on('scheduled-trigger', (_e, task) => cb(task)),
  onExtensionPing: (cb) => ipcRenderer.on('extension-ping', (_e, data) => cb(data)),
  cancelDownload: () => ipcRenderer.send('cancel-download'),
  retryItem: (payload) => ipcRenderer.send('retry-item', payload),
  selectDownloadFolder: () => ipcRenderer.invoke('select-download-folder'),
  getSavedFolder: () => ipcRenderer.invoke('get-saved-folder'),
  openFolder: () => ipcRenderer.invoke('open-folder'),
  revealFile: (filepath) => ipcRenderer.invoke('reveal-file', filepath),

  // settings
  getSettings: () => ipcRenderer.invoke('get-settings'),
  updateSettings: (patch) => ipcRenderer.invoke('update-settings', patch),

  // yt-dlp updater
  updateYtdlp: () => ipcRenderer.invoke('update-ytdlp'),
  onYtdlpUpdateStatus: (cb) => ipcRenderer.on('ytdlp-update-status', (_e, data) => cb(data)),
  onTriggerUpdateYtdlp: (cb) => ipcRenderer.on('trigger-update-ytdlp', () => cb()),
  onNotify: (cb) => ipcRenderer.on('notify', (_e, msg) => cb(msg)),

  // history
  getHistory: () => ipcRenderer.invoke('get-history'),
  clearHistory: () => ipcRenderer.invoke('clear-history'),
  deleteHistoryEntry: (id) => ipcRenderer.invoke('delete-history-entry', id),

  // events
  onMeta: (cb) => ipcRenderer.on('download-meta', (_e, meta) => cb(meta)),
  onPlaylistItems: (cb) => ipcRenderer.on('playlist-items', (_e, items) => cb(items)),
  onItemState: (cb) => ipcRenderer.on('item-state', (_e, data) => cb(data)),
  onStatus: (cb) => ipcRenderer.on('download-status', (_e, msg) => cb(msg)),
  onProgress: (cb) => ipcRenderer.on('download-progress', (_e, data) => cb(data)),
  onComplete: (cb) => ipcRenderer.on('download-complete', (_e, data) => cb(data)),
  onError: (cb) => ipcRenderer.on('download-error', (_e, msg) => cb(msg)),
  onHistoryUpdated: (cb) => ipcRenderer.on('history-updated', (_e, data) => cb(data)),
});
